#!/bin/bash

read_keystore_info() {
  local config_file="auto.config"
  local keystore_entry

  # Read the KEYSORE line from the config file
  keystore_entry=$(grep "^KEYSTORE=" "$config_file" | cut -d'=' -f2-)

  if [[ -n $keystore_entry ]]; then
    # Split the KEYSORE entry into an array using comma as delimiter
    IFS=',' read -r -a addr <<< "$keystore_entry"

    # Iterate over each keystore entry
    for keystore_data in "${addr[@]}"; do
      # Further split each part by the ':' delimiter
      IFS=':' read -r -a keyparts <<< "$keystore_data"
      local keystore_path="${keyparts[0]}"
      local keystore_alias="${keyparts[1]}"
      local keystore_password="${keyparts[2]}"

      echo "Keystore Path: $keystore_path"
      echo "Keystore Alias: $keystore_alias"
      echo "Keystore Password: $keystore_password"
      echo # Newline for readability between multiple entries
    done
  else
    echo "The KEYSORE variable was not found in the config file."
  fi
}

# Call the function
read_keystore_info