#!/bin/bash

# Load config file
source .config

# Function to install dependencies
install_dependencies() {
    IFS=',' read -ra PACKAGES <<< "$DEPENDENCIES"
    for pkg in "${PACKAGES[@]}"; do
        pkg=$(echo "$pkg" | xargs)  # Trim whitespace
        echo "Installing $pkg..."
        sudo yum install -y "$pkg"
    done
}

# Function to transfer users
transfer_user() {
    IFS=',' read -ra ADDR <<< "$USERS"
    for user in "${ADDR[@]}"; do
        echo "Transferring user: $user"
        rsync -avzp "$SOURCE_SERVER:/home/$user" /home/
    done
}

# Function to transfer data with disk space check and excluding NFS mounts
transfer_data() {
    IFS=',' read -ra ADDR <<< "$DISKS_TO_TRANSFER"
    for disk in "${ADDR[@]}"; do
        echo "Preparing to transfer $disk from $SOURCE_SERVER..."

        # Generate exclude options for NFS mounts under this disk on the source server
        EXCLUDE_DIRS=$(ssh "$SOURCE_SERVER" "mount -t nfs | grep '$disk' | awk -F' ' '{n=split(\$3,parts,\"/\"); print \"--exclude=\"parts[n]}'" | tr '\n' ' ')

        # Get the size of the directory on the source server
        local size_source=$(ssh "$SOURCE_SERVER" "du -s '$disk' | cut -f1")
        
        # Get available disk space on the target directory
        local size_target=$(df --output=avail -k "$(dirname $disk)" | tail -1)

        if [ "$size_source" -lt "$size_target" ]; then
            echo "Sufficient space found. Transferring $disk with exclusions..."
            rsync -avzP --perms --progress -e ssh $EXCLUDE_DIRS "$SOURCE_SERVER:$disk" "$disk"
        else
            echo "Not enough space on target for $disk. Transfer skipped."
        fi
    done
}

# Function to process config files
process_config_files() {
    IFS=',' read -ra FILES <<< "$CONFIG_FILES"
    for file in "${FILES[@]}"; do
        echo "Processing $file..."

        # Copy the file from the source to the target server using rsync
        rsync -avzp "$SOURCE_SERVER:$file" "$file"

        # Replace the source hostname with the target hostname
        sed -i "s/$SOURCE_HOSTNAME/$TARGET_HOSTNAME/g" "$file"
    done
}

# Execute functions
install_dependencies
transfer_user
transfer_data
process_config_files
